name: Runner SSH
on: workflow_dispatch
jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TS_AUTHKEY }}
          hostname: gh-runner

      - name: Nyalain SSH + Tampilkan IP
        run: |
          sudo apt-get update -y
          sudo apt-get install -y openssh-server
          echo "runner:runner" | sudo chpasswd
          sudo service ssh start
          echo "=========================="
          tailscale ip -4
          echo "SSH: ssh runner@$(tailscale ip -4)"
          echo "Pass: runner"
          echo "=========================="
          sleep 21600
